DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS bitly;

CREATE TABLE users(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  paid BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE bitly(
  id SERIAL PRIMARY KEY NOT NULL,
  longURL VARCHAR(255) NOT NULL,
  u VARCHAR(10),
  created_at DATE NOT NULL,
  userID INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) DEFAULT longURL
);